{
"@R":"1343723841",
"eredirect":"",
"redirect":"",
"pre_action":"action:\/\/yslowviewer-action\/yslowviewer\/AccountAction",
"post_action":"",
"session_exp":"2147483647",
"expires":"0",
"header":"",
"pheader":"",
"bottom":"",
"layout":{
"type":"HorizontalWidget",
"component":"component:\/\/core-component\/default\/horizontal#critical",
"extra":null,
"children":[

]
},
"_u":"login"
}