{
"@R":"1334022655",
"eredirect":"",
"redirect":"",
"pre_action":"action:\/\/yslowviewer-action\/yslowviewer\/NetexportAction?set",
"post_action":"",
"session_exp":"2147483647",
"expires":"0",
"header":null,
"pheader":"",
"bottom":"",
"layout":{
"type":"PlainWidget",
"extra":"",
"component":"component:\/\/core-component\/default\/plain?get",
"children":[

]
},
"_u":"nepost"
}