{
"@R":"1343723735",
"eredirect":"",
"redirect":"",
"pre_action":"action:\/\/yslowviewer-action\/yslowviewer\/AccountAction",
"post_action":"",
"session_exp":"2147483647",
"expires":"0",
"header":"",
"pheader":"",
"bottom":"",
"layout":{
"type":"HorizontalWidget",
"extra":"",
"component":"component:\/\/core-component\/default\/utils\/profile?get",
"children":[

]
},
"_u":"profile"
}