{
"@R":"1334022667",
"eredirect":"",
"redirect":"",
"pre_action":"",
"post_action":"action:\/\/yslowviewer-action\/yslowviewer\/PagespeedAction?set",
"session_exp":"2147483647",
"expires":"0",
"header":null,
"pheader":"",
"bottom":"",
"layout":{
"type":"PlainWidget",
"extra":"",
"component":"component:\/\/core-component\/default\/plain?get",
"children":[

]
},
"_u":"pspost"
}