{
"@R":"1362386336",
"type":"HorizontalWidget",
"subject":"gettippage",
"description":"",
"css":"",
"js":"",
"id":"",
"class":"",
"body":"",
"action":[
"action:\/\/mongo-action\/mongo\/TipAction?get"
],
"header":"",
"bottom":"",
"_u":"tips\/gettippage"
}