{
"@R":"1362554489",
"type":"HorizontalWidget",
"subject":"getexampage",
"description":"",
"css":"",
"js":"",
"id":"",
"class":"",
"body":"",
"action":[
"action:\/\/mongo-action\/mongo\/ExamAction?get"
],
"header":"",
"bottom":"",
"_u":"exams\/getexampage"
}