{
"@R":"1368767593",
"type":"JsonWidget",
"subject":"gettimetablepage",
"description":"",
"css":"",
"js":"",
"id":"",
"class":"",
"body":"mongo.docs",
"action":[
"action://mongo-action/mongo/TimetableAction?getA"
],
"header":"",
"bottom":"",
"_u":"noryo2013/timetable/gettimetablepage"
}