{
"@R":"1361775547",
"type":"HorizontalWidget",
"subject":"getpage",
"description":"",
"css":"",
"js":"",
"id":"",
"class":"",
"body":"",
"action":[
"action:\/\/mongo-action\/mongo\/PageAction?get#cache#cexp=30"
],
"header":"",
"bottom":"",
"_u":"pages\/getpage"
}